# Generated by Django 5.1.7 on 2025-03-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraccount_age'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['name'], name='account_use_name_0cdc5d_idx'),
        ),
    ]
