# Generated by Django 5.1.7 on 2025-03-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_useraccount_account_use_name_0cdc5d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='lastname',
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
    ]
